In [1]:
# load libraies

%run py_libraries.py

/Users/4476224/.local/lib/python3.8/site-packages/tensorflow_addons/utils/ensure_tf_install.py:53: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.6.0 and strictly below 2.9.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 2.13.0 and is not supported. 
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version. 
You can find the compatibility matrix in TensorFlow Addon's readme:
https://github.com/tensorflow/addons
  warnings.warn(


Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
# Ext Validation set, clinical trial data

# load data
data = pd.read_excel('data/BladderCancer_Ex_Val_clini_trial.xlsx')
data = data.loc[0:13]

In [3]:
#

cols = data.columns.tolist()
print(cols)

['ID', 'Age_at_Surgery', 'Race', 'Surgery', 'Smoker', 'BMI', 'NAC', 'cT', 'pT', 'cT_or_pT', 'pN', 'Bx_Histology', 'Histology', 'Secondary_Histology', 'Sample_weight_g_tumor', 'Tumor_digest_count_primary_tumor', 'Number_of_fragments_plated_tumor', 'Overall_TIL_growth']


In [4]:


Ndata = data[['ID','Age_at_Surgery','Race','Surgery','Smoker','BMI',\
              'NAC','cT','pT','cT_or_pT','pN','Bx_Histology','Histology',\
              'Sample_weight_g_tumor','Tumor_digest_count_primary_tumor','Number_of_fragments_plated_tumor',\
              'Overall_TIL_growth']].copy()

# 'Surgeon'
Ndata = Ndata.replace(to_replace="Yes",value="Yes_TIL")
Ndata = Ndata.replace(to_replace="No",value="No_TIL")

Ndata = Ndata.replace(r'^\s*$', np.nan, regex=True) # Replace Blank values with DataFrame.replace() methods.

Extracted_col0 = Ndata.iloc[:,0:1]  # "ID"                         
Extracted_col2 = Ndata['Age_at_Surgery']
Extracted_col3 = Ndata['Race'];                              Extracted_col4 = Ndata['Surgery']
Extracted_col5 = Ndata['Smoker'];                            Extracted_col6 = Ndata['BMI']
Extracted_col7 = Ndata['NAC'];                               Extracted_col8 = Ndata['cT']
Extracted_col9 = Ndata['pT'];                                Extracted_col10 = Ndata['cT_or_pT']
Extracted_col11 = Ndata['pN'];                               Extracted_col12 = Ndata['Bx_Histology']
Extracted_col13 = Ndata['Histology'];                        Extracted_col14 = Ndata['Sample_weight_g_tumor']
Extracted_col15 = Ndata['Tumor_digest_count_primary_tumor']; Extracted_col16 = Ndata['Number_of_fragments_plated_tumor']
Extracted_col17 = Ndata['Overall_TIL_growth']

ndata_sel0 = Extracted_col0
ndata_sel0 = ndata_sel0.join(Extracted_col2)
ndata_sel0 = ndata_sel0.join(Extracted_col3); ndata_sel0 = ndata_sel0.join(Extracted_col4)
ndata_sel0 = ndata_sel0.join(Extracted_col5); ndata_sel0 = ndata_sel0.join(Extracted_col6)
ndata_sel0 = ndata_sel0.join(Extracted_col7); ndata_sel0 = ndata_sel0.join(Extracted_col8)
ndata_sel0 = ndata_sel0.join(Extracted_col9); ndata_sel0 = ndata_sel0.join(Extracted_col10)
ndata_sel0 = ndata_sel0.join(Extracted_col11); ndata_sel0 = ndata_sel0.join(Extracted_col12)
ndata_sel0 = ndata_sel0.join(Extracted_col13); ndata_sel0 = ndata_sel0.join(Extracted_col14)
ndata_sel0 = ndata_sel0.join(Extracted_col15); ndata_sel0 = ndata_sel0.join(Extracted_col16)
ndata_sel0 = ndata_sel0.join(Extracted_col17)

ndata_sel0 = ndata_sel0.rename(columns={'Overall_TIL_growth': 'OverallTILGrowth'})
ndata_sel0 = ndata_sel0.rename(columns={'Tumor_digest_count_primary_tumor': 'Tumor_digest_count'})
ndata_sel0 = ndata_sel0.rename(columns={'Sample_weight_g_tumor': 'Sample_weight'})
ndata_sel0 = ndata_sel0.rename(columns={'Number_of_fragments_plated_tumor': 'Fragments_plated'})

Cols = ['Age at Surgery','Race','Surgery','Smoker','BMI',\
        'NAC','cT','pT','cT or pT','pN','Bx Histology','Histology',\
        'Sample weight','Tumor digest count','Fragments plated',\
        'OverallTILGrowth']

feats = ['Age at Surgery','Race','Surgery','Smoker','BMI',\
        'NAC','cT','pT','cT or pT','pN','Bx Histology','Histology',\
        'Sample weight','Tumor digest count','Fragments plated']

feat_labels = feats

In [5]:
ndata_sel = ndata_sel0.dropna(subset=['OverallTILGrowth'])

print(ndata_sel.count())
print(ndata_sel.shape)

ID                    14
Age_at_Surgery        14
Race                  14
Surgery               14
Smoker                14
BMI                   14
NAC                    5
cT                    14
pT                     4
cT_or_pT              14
pN                     4
Bx_Histology           5
Histology              4
Sample_weight         14
Tumor_digest_count     5
Fragments_plated      14
OverallTILGrowth      14
dtype: int64
(14, 17)


In [6]:
ndata_sel.Race.unique()

array([1])

In [7]:
ndata_sel['Race'] = ndata_sel['Race'].replace(to_replace=0,value='Unknown')
ndata_sel['Race'] = ndata_sel['Race'].replace(to_replace=1,value='White')
ndata_sel['Race'] = ndata_sel['Race'].replace(to_replace=2,value='Black')
ndata_sel['Race'] = ndata_sel['Race'].replace(to_replace=3,value='Asian')
ndata_sel['Race'] = ndata_sel['Race'].replace(to_replace=4,value='Pacific Islander')
ndata_sel['Race'] = ndata_sel['Race'].replace(to_replace=5,value='American Indian / Alaskan Native')

ndata_sel.Race.unique()

array(['White'], dtype=object)

In [8]:
ndata_sel.Surgery.unique()

array([2, 1])

In [9]:
ndata_sel['Surgery'] = ndata_sel['Surgery'].replace(to_replace=1,value='Radical Cystectomy')
ndata_sel['Surgery'] = ndata_sel['Surgery'].replace(to_replace=2,value='TURBT')

ndata_sel.Surgery.unique()

array(['TURBT', 'Radical Cystectomy'], dtype=object)

In [10]:
ndata_sel.Smoker.unique()

array([0, 1, 2])

In [11]:
ndata_sel['Smoker'] = ndata_sel['Smoker'].replace(to_replace=0,value='Never Smoked')
ndata_sel['Smoker'] = ndata_sel['Smoker'].replace(to_replace=1,value='Ever Smoked')
ndata_sel['Smoker'] = ndata_sel['Smoker'].replace(to_replace=2,value='Current Smoker')
ndata_sel['Smoker'] = ndata_sel['Smoker'].replace(to_replace=3,value='Not Reported')

ndata_sel.Smoker.unique()

array(['Never Smoked', 'Ever Smoked', 'Current Smoker'], dtype=object)

In [12]:
ndata_sel.NAC.unique()

array([ 0.,  1., nan])

In [13]:
ndata_sel['NAC'] = ndata_sel['NAC'].replace(to_replace=0,value='no NAC')
ndata_sel['NAC'] = ndata_sel['NAC'].replace(to_replace=1,value='NAC')

ndata_sel.NAC.unique()

array(['no NAC', 'NAC', nan], dtype=object)

In [14]:
ndata_sel.cT.unique()

array([3, 4, 1, 2])

In [15]:
ndata_sel['cT'] = ndata_sel['cT'].replace(to_replace=0,value='T0')
ndata_sel['cT'] = ndata_sel['cT'].replace(to_replace=1,value='Ta')
ndata_sel['cT'] = ndata_sel['cT'].replace(to_replace=2,value='CIS')
ndata_sel['cT'] = ndata_sel['cT'].replace(to_replace=3,value='T1')
ndata_sel['cT'] = ndata_sel['cT'].replace(to_replace=4,value='T2')
ndata_sel['cT'] = ndata_sel['cT'].replace(to_replace=5,value='T2')
ndata_sel['cT'] = ndata_sel['cT'].replace(to_replace=6,value='T2')
ndata_sel['cT'] = ndata_sel['cT'].replace(to_replace=7,value='T3')
ndata_sel['cT'] = ndata_sel['cT'].replace(to_replace=8,value='T3')
ndata_sel['cT'] = ndata_sel['cT'].replace(to_replace=9,value='T3')
ndata_sel['cT'] = ndata_sel['cT'].replace(to_replace=10,value='T4')
ndata_sel['cT'] = ndata_sel['cT'].replace(to_replace=11,value='T4')
ndata_sel['cT'] = ndata_sel['cT'].replace(to_replace=12,value='T4')
ndata_sel['cT'] = ndata_sel['cT'].replace(to_replace=13,value='Tx')

ndata_sel.cT.unique()

array(['T1', 'T2', 'Ta', 'CIS'], dtype=object)

In [16]:
ndata_sel.pT.unique()

array([nan,  5.,  2.,  1., 11.])

In [17]:
ndata_sel['pT'] = ndata_sel['pT'].replace(to_replace=0,value='T0')
ndata_sel['pT'] = ndata_sel['pT'].replace(to_replace=1,value='Ta')
ndata_sel['pT'] = ndata_sel['pT'].replace(to_replace=2,value='CIS')
ndata_sel['pT'] = ndata_sel['pT'].replace(to_replace=3,value='T1')
ndata_sel['pT'] = ndata_sel['pT'].replace(to_replace=4,value='T2')
ndata_sel['pT'] = ndata_sel['pT'].replace(to_replace=5,value='T2')
ndata_sel['pT'] = ndata_sel['pT'].replace(to_replace=6,value='T2')
ndata_sel['pT'] = ndata_sel['pT'].replace(to_replace=7,value='T3')
ndata_sel['pT'] = ndata_sel['pT'].replace(to_replace=8,value='T3')
ndata_sel['pT'] = ndata_sel['pT'].replace(to_replace=9,value='T3')
ndata_sel['pT'] = ndata_sel['pT'].replace(to_replace=10,value='T4')
ndata_sel['pT'] = ndata_sel['pT'].replace(to_replace=11,value='T4')
ndata_sel['pT'] = ndata_sel['pT'].replace(to_replace=12,value='T4')
ndata_sel['pT'] = ndata_sel['pT'].replace(to_replace=13,value='Tx')

ndata_sel.pT.unique()

array([nan, 'T2', 'CIS', 'Ta', 'T4'], dtype=object)

In [18]:
ndata_sel.cT_or_pT.unique()

array([ 3,  5,  4, 11,  1,  2])

In [19]:
ndata_sel['cT_or_pT'] = ndata_sel['cT_or_pT'].replace(to_replace=0,value='T0')
ndata_sel['cT_or_pT'] = ndata_sel['cT_or_pT'].replace(to_replace=1,value='Ta')
ndata_sel['cT_or_pT'] = ndata_sel['cT_or_pT'].replace(to_replace=2,value='CIS')
ndata_sel['cT_or_pT'] = ndata_sel['cT_or_pT'].replace(to_replace=3,value='T1')
ndata_sel['cT_or_pT'] = ndata_sel['cT_or_pT'].replace(to_replace=4,value='T2')
ndata_sel['cT_or_pT'] = ndata_sel['cT_or_pT'].replace(to_replace=5,value='T2')
ndata_sel['cT_or_pT'] = ndata_sel['cT_or_pT'].replace(to_replace=6,value='T2')
ndata_sel['cT_or_pT'] = ndata_sel['cT_or_pT'].replace(to_replace=7,value='T3')
ndata_sel['cT_or_pT'] = ndata_sel['cT_or_pT'].replace(to_replace=8,value='T3')
ndata_sel['cT_or_pT'] = ndata_sel['cT_or_pT'].replace(to_replace=9,value='T3')
ndata_sel['cT_or_pT'] = ndata_sel['cT_or_pT'].replace(to_replace=10,value='T4')
ndata_sel['cT_or_pT'] = ndata_sel['cT_or_pT'].replace(to_replace=11,value='T4')
ndata_sel['cT_or_pT'] = ndata_sel['cT_or_pT'].replace(to_replace=12,value='T4')
ndata_sel['cT_or_pT'] = ndata_sel['cT_or_pT'].replace(to_replace=13,value='Tx')

ndata_sel.cT_or_pT.unique()

array(['T1', 'T2', 'T4', 'Ta', 'CIS'], dtype=object)

In [20]:
ndata_sel.pN.unique()

array([nan,  0.])

In [21]:
ndata_sel['pN'] = ndata_sel['pN'].replace(to_replace=0,value='N0')
ndata_sel['pN'] = ndata_sel['pN'].replace(to_replace=1,value='N1')
ndata_sel['pN'] = ndata_sel['pN'].replace(to_replace=2,value='N2')
ndata_sel['pN'] = ndata_sel['pN'].replace(to_replace=3,value='N3')
ndata_sel['pN'] = ndata_sel['pN'].replace(to_replace=4,value='Nx')

ndata_sel.pN.unique()

array([nan, 'N0'], dtype=object)

In [22]:
ndata_sel.Bx_Histology.unique()

array([ 1., nan])

In [23]:
ndata_sel['Bx_Histology'] = ndata_sel['Bx_Histology'].replace(to_replace=0,value='Benign')
ndata_sel['Bx_Histology'] = ndata_sel['Bx_Histology'].replace(to_replace=1,value='Urothelial Carcinoma')
ndata_sel['Bx_Histology'] = ndata_sel['Bx_Histology'].replace(to_replace=2,value='Squamous Cell Carcinoma')
ndata_sel['Bx_Histology'] = ndata_sel['Bx_Histology'].replace(to_replace=3,value='Adenocarcinoma')
ndata_sel['Bx_Histology'] = ndata_sel['Bx_Histology'].replace(to_replace=4,value='Urothelial Carcinoma')
ndata_sel['Bx_Histology'] = ndata_sel['Bx_Histology'].replace(to_replace=5,value='Urothelial Carcinoma')
ndata_sel['Bx_Histology'] = ndata_sel['Bx_Histology'].replace(to_replace=6,value='Urothelial Carcinoma')
ndata_sel['Bx_Histology'] = ndata_sel['Bx_Histology'].replace(to_replace=7,value='Urothelial Carcinoma')
ndata_sel['Bx_Histology'] = ndata_sel['Bx_Histology'].replace(to_replace=8,value='Small Cell Carcinoma')
ndata_sel['Bx_Histology'] = ndata_sel['Bx_Histology'].replace(to_replace=9,value='Urothelial Carcinoma')
ndata_sel['Bx_Histology'] = ndata_sel['Bx_Histology'].replace(to_replace=10,value='Urothelial Carcinoma')
ndata_sel['Bx_Histology'] = ndata_sel['Bx_Histology'].replace(to_replace=11,value='Urothelial Carcinoma')
ndata_sel['Bx_Histology'] = ndata_sel['Bx_Histology'].replace(to_replace=12,value='Urothelial Carcinoma')
ndata_sel['Bx_Histology'] = ndata_sel['Bx_Histology'].replace(to_replace=13,value='Urothelial Carcinoma')

ndata_sel.Bx_Histology.unique()

array(['Urothelial Carcinoma', nan], dtype=object)

In [24]:
ndata_sel.Histology.unique()

array([nan,  1.])

In [25]:
ndata_sel['Histology'] = ndata_sel['Histology'].replace(to_replace=0,value='Benign')
ndata_sel['Histology'] = ndata_sel['Histology'].replace(to_replace=1,value='Urothelial Carcinoma')
ndata_sel['Histology'] = ndata_sel['Histology'].replace(to_replace=2,value='Squamous Cell Carcinoma')
ndata_sel['Histology'] = ndata_sel['Histology'].replace(to_replace=3,value='Adenocarcinoma')
ndata_sel['Histology'] = ndata_sel['Histology'].replace(to_replace=4,value='Urothelial Carcinoma')
ndata_sel['Histology'] = ndata_sel['Histology'].replace(to_replace=5,value='Urothelial Carcinoma')
ndata_sel['Histology'] = ndata_sel['Histology'].replace(to_replace=6,value='Urothelial Carcinoma')
ndata_sel['Histology'] = ndata_sel['Histology'].replace(to_replace=7,value='Urothelial Carcinoma')
ndata_sel['Histology'] = ndata_sel['Histology'].replace(to_replace=8,value='Small Cell Carcinoma')
ndata_sel['Histology'] = ndata_sel['Histology'].replace(to_replace=9,value='Urothelial Carcinoma')
ndata_sel['Histology'] = ndata_sel['Histology'].replace(to_replace=10,value='Urothelial Carcinoma')
ndata_sel['Histology'] = ndata_sel['Histology'].replace(to_replace=11,value='Urothelial Carcinoma')
ndata_sel['Histology'] = ndata_sel['Histology'].replace(to_replace=12,value='Urothelial Carcinoma')
ndata_sel['Histology'] = ndata_sel['Histology'].replace(to_replace=13,value='Urothelial Carcinoma')

ndata_sel.Histology.unique()

array([nan, 'Urothelial Carcinoma'], dtype=object)

In [26]:
ndata_sel.Fragments_plated.unique()

array([ 5, 12,  6,  8,  7, 15, 48, 35, 28, 14, 13])

In [27]:
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=0,value='0 - 5')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=1,value='0 - 5')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=2,value='0 - 5')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=3,value='0 - 5')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=4,value='0 - 5')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=5,value='0 - 5')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=6,value='6 - 11')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=7,value='6 - 11')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=8,value='6 - 11')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=9,value='6 - 11')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=10,value='6 - 11')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=11,value='6 - 11')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=12,value='12 - 17')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=13,value='12 - 17')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=14,value='12 - 17')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=15,value='12 - 17')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=16,value='12 - 17')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=17,value='12 - 17')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=18,value='18 - 23')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=19,value='18 - 23')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=20,value='18 - 23')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=21,value='18 - 23')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=22,value='18 - 23')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=23,value='18 - 23')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=24,value='>= 24')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=28,value='>= 24')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=32,value='>= 24')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=35,value='>= 24')
ndata_sel['Fragments_plated'] = ndata_sel['Fragments_plated'].replace(to_replace=48,value='>= 24')

ndata_sel.Fragments_plated.unique()

array(['0 - 5', '12 - 17', '6 - 11', '>= 24'], dtype=object)

In [28]:
ndata_sel.OverallTILGrowth.unique()

array(['Yes_TIL'], dtype=object)

In [29]:
ndata_sel['OverallTILGrowth'] = ndata_sel['OverallTILGrowth'].replace(to_replace='No_TIL',value='TIL')
ndata_sel['OverallTILGrowth'] = ndata_sel['OverallTILGrowth'].replace(to_replace='Yes_TIL',value='TIL')

ndata_sel.OverallTILGrowth.unique()

array(['TIL'], dtype=object)

In [30]:
# ndata_sel = ndata_sel.rename(columns={'Overall_TIL_growth': 'OverallTILGrowth'})
ndata_sel = ndata_sel.rename(columns={'Age_at_Surgery': 'Age at Surgery'})
ndata_sel = ndata_sel.rename(columns={'cT_or_pT': 'cT or pT'})
ndata_sel = ndata_sel.rename(columns={'Bx_Histology': 'Bx Histology'})
ndata_sel = ndata_sel.rename(columns={'Sample_weight': 'Sample weight'})
ndata_sel = ndata_sel.rename(columns={'Tumor_digest_count': 'Tumor digest count'})
ndata_sel = ndata_sel.rename(columns={'Fragments_plated': 'Fragments plated'})

Cols = ['Age at Surgery','Race','Surgery','Smoker','BMI',\
        'NAC','cT','pT','cT or pT','pN','Bx Histology','Histology',\
        'Sample weight','Tumor digest count','Fragments plated',\
        'OverallTILGrowth']

In [31]:
# generate table 

col_tab = ['Age at Surgery','Race','Surgery','Smoker','BMI',\
        'NAC','cT','pT','cT or pT','pN','Bx Histology','Histology',\
        'Sample weight','Tumor digest count','Fragments plated',\
        'OverallTILGrowth']


categorical = ['Race','Surgery','Smoker','NAC','cT','pT','cT or pT','pN','Bx Histology','Histology',\
               'Fragments plated','OverallTILGrowth']

groupby = ['OverallTILGrowth']

myTable_data = TableOne(ndata_sel,columns=col_tab,categorical=categorical) #,groupby=groupby,pval=True)

print(myTable_data.tabulate(tablefmt="latex"))


\begin{tabular}{llll}
\hline
                               &                      & Missing   & Overall                  \\
\hline
 n                             &                      &           & 14                       \\
 Age at Surgery, mean (SD)     &                      & 0         & 70.4 (6.9)               \\
 Race, n (\%)                   & White                & 0         & 14 (100.0)               \\
 Surgery, n (\%)                & Radical Cystectomy   & 0         & 4 (28.6)                 \\
                               & TURBT                &           & 10 (71.4)                \\
 Smoker, n (\%)                 & Current Smoker       & 0         & 1 (7.1)                  \\
                               & Ever Smoked          &           & 7 (50.0)                 \\
                               & Never Smoked         &           & 6 (42.9)                 \\
 BMI, mean (SD)                &                      & 0         & 28.7 (5.8)               \\
 